#!/usr/bin/env node
// EM Fitness: builds the per-language exercise name packs in frontend/src/names/ from the
// hand-kept tables scripts/names-<lang>.json ({ exerciseId: "translated name" }).
// The upstream dataset only ships English names, so these tables are ours to edit;
// English stays inline in exercises-data.js as `n`.
//
//   node scripts/build-names.mjs
//
// Fails if a table misses a dataset id, has an id the dataset doesn't, or an empty name.

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = join(root, 'frontend', 'src', 'names')
const { EXDB } = await import(pathToFileURL(join(root, 'frontend', 'src', 'lib', 'exercises-data.js')).href)
const ids = EXDB.map(e => e.id)

mkdirSync(outDir, { recursive: true })
const tables = readdirSync(join(root, 'scripts')).filter(f => /^names-[a-z]{2}\.json$/.test(f))
if (!tables.length) throw new Error('No scripts/names-<lang>.json tables found')
for (const f of tables) {
  const lang = f.slice(6, 8)
  const table = JSON.parse(readFileSync(join(root, 'scripts', f), 'utf8'))
  const missing = ids.filter(id => typeof table[id] !== 'string' || !table[id].trim())
  const extra = Object.keys(table).filter(id => !ids.includes(id))
  if (missing.length || extra.length) throw new Error(`${f}: missing ${missing.join(',') || '-'} · unknown ${extra.join(',') || '-'}`)
  const pack = {}
  // Sentence case: the UI only upper-cases the first letter outside English, and not in
  // inline spots (spans, flex rows), so the pack carries it.
  const cap = s => s.charAt(0).toLocaleUpperCase(lang) + s.slice(1)
  ids.forEach(id => { pack[id] = cap(table[id].trim()) })
  const file = join(outDir, lang + '.js')
  writeFileSync(file, '// generated by scripts/build-names.mjs from scripts/' + f + ' — do not edit\nexport default ' + JSON.stringify(pack) + '\n')
  console.log(`${file}: ${ids.length} exercises`)
}
